<head>
    <style>
        table, th, td {
            border: 0.5px solid #333;
            border-collapse: collapse;
            font-family: 'Inter', sans-serif;
            padding: 0.375rem;
            font-size: 0.75rem;
            line-height: 1rem;
        }
        table {
            width: 100%;
        }
        th {
            background-color: #ccc;
        }
        .header {
            text-align: center;
            margin-top: 50px;
        }
        @page {
          header: page-header;
          footer: page-footer;
        }
    </style>
</head>
<body>
        
<htmlpageheader name="page-header">
    <div class="header">
        <br>
        <h3 style="">Toggi Shipping & Logistics Ltd</h3>
        <h4>Bashundhara group</h4>
    </div>
</htmlpageheader>

@yield('content')

<htmlpagefooter name="page-footer">
    <span style="color: #666">Generated by: Torony VMS</span>
</htmlpagefooter>


</body>
