<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Permission;

class OperationPermissionSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $operationPermissions = [
            ['menu' => 'Operations', 'subject' => 'Cargo Tariff', 'name' => 'ops-cargo-tariff-view'],
            ['menu' => 'Operations', 'subject' => 'Cargo Tariff', 'name' => 'ops-cargo-tariff-create'],
            ['menu' => 'Operations', 'subject' => 'Cargo Tariff', 'name' => 'ops-cargo-tariff-edit'],
            ['menu' => 'Operations', 'subject' => 'Cargo Tariff', 'name' => 'ops-cargo-tariff-delete'],
            ['menu' => 'Operations', 'subject' => 'Cargo Type', 'name' => 'ops-cargo-type-view'],
            ['menu' => 'Operations', 'subject' => 'Cargo Type', 'name' => 'ops-cargo-type-create'],
            ['menu' => 'Operations', 'subject' => 'Cargo Type', 'name' => 'ops-cargo-type-edit'],
            ['menu' => 'Operations', 'subject' => 'Cargo Type', 'name' => 'ops-cargo-type-delete'],
            ['menu' => 'Operations', 'subject' => 'Expense Head', 'name' => 'ops-expense-head-view'],
            ['menu' => 'Operations', 'subject' => 'Expense Head', 'name' => 'ops-expense-head-create'],
            ['menu' => 'Operations', 'subject' => 'Expense Head', 'name' => 'ops-expense-head-edit'],
            ['menu' => 'Operations', 'subject' => 'Expense Head', 'name' => 'ops-expense-head-delete'],
            ['menu' => 'Operations', 'subject' => 'Maritime Certificate', 'name' => 'ops-maritime-certificate-view'],
            ['menu' => 'Operations', 'subject' => 'Maritime Certificate', 'name' => 'ops-maritime-certificate-create'],
            ['menu' => 'Operations', 'subject' => 'Maritime Certificate', 'name' => 'ops-maritime-certificate-edit'],
            ['menu' => 'Operations', 'subject' => 'Maritime Certificate', 'name' => 'ops-maritime-certificate-delete'],
            ['menu' => 'Operations', 'subject' => 'Port', 'name' => 'ops-port-view'],
            ['menu' => 'Operations', 'subject' => 'Port', 'name' => 'ops-port-create'],
            ['menu' => 'Operations', 'subject' => 'Port', 'name' => 'ops-port-edit'],
            ['menu' => 'Operations', 'subject' => 'Port', 'name' => 'ops-port-delete'],
            ['menu' => 'Operations', 'subject' => 'Customer', 'name' => 'ops-customer-view'],
            ['menu' => 'Operations', 'subject' => 'Customer', 'name' => 'ops-customer-create'],
            ['menu' => 'Operations', 'subject' => 'Customer', 'name' => 'ops-customer-edit'],
            ['menu' => 'Operations', 'subject' => 'Customer', 'name' => 'ops-customer-delete'],
            ['menu' => 'Operations', 'subject' => 'Customer Invoice', 'name' => 'ops-customer-invoice-view'],
            ['menu' => 'Operations', 'subject' => 'Customer Invoice', 'name' => 'ops-customer-invoice-create'],
            ['menu' => 'Operations', 'subject' => 'Customer Invoice', 'name' => 'ops-customer-invoice-edit'],
            ['menu' => 'Operations', 'subject' => 'Customer Invoice', 'name' => 'ops-customer-invoice-delete'],
            ['menu' => 'Operations', 'subject' => 'Vessel', 'name' => 'ops-vessel-view'],
            ['menu' => 'Operations', 'subject' => 'Vessel', 'name' => 'ops-vessel-create'],
            ['menu' => 'Operations', 'subject' => 'Vessel', 'name' => 'ops-vessel-edit'],
            ['menu' => 'Operations', 'subject' => 'Vessel', 'name' => 'ops-vessel-delete'],
            ['menu' => 'Operations', 'subject' => 'Vessel Certificate', 'name' => 'ops-vessel-certificate-view'],
            ['menu' => 'Operations', 'subject' => 'Vessel Certificate', 'name' => 'ops-vessel-certificate-create'],
            ['menu' => 'Operations', 'subject' => 'Vessel Certificate', 'name' => 'ops-vessel-certificate-edit'],
            ['menu' => 'Operations', 'subject' => 'Vessel Certificate', 'name' => 'ops-vessel-certificate-delete'],
            ['menu' => 'Operations', 'subject' => 'Vessel Expense Head', 'name' => 'ops-vessel-expense-head-view'],
            ['menu' => 'Operations', 'subject' => 'Vessel Expense Head', 'name' => 'ops-vessel-expense-head-create'],
            ['menu' => 'Operations', 'subject' => 'Vessel Expense Head', 'name' => 'ops-vessel-expense-head-edit'],
            ['menu' => 'Operations', 'subject' => 'Vessel Expense Head', 'name' => 'ops-vessel-expense-head-delete'],
            ['menu' => 'Operations', 'subject' => 'Vessel Particular', 'name' => 'ops-vessel-particular-view'],
            ['menu' => 'Operations', 'subject' => 'Vessel Particular', 'name' => 'ops-vessel-particular-create'],
            ['menu' => 'Operations', 'subject' => 'Vessel Particular', 'name' => 'ops-vessel-particular-edit'],
            ['menu' => 'Operations', 'subject' => 'Vessel Particular', 'name' => 'ops-vessel-particular-delete'],
            ['menu' => 'Operations', 'subject' => 'Charterer Profile', 'name' => 'ops-charterer-profile-view'],
            ['menu' => 'Operations', 'subject' => 'Charterer Profile', 'name' => 'ops-charterer-profile-create'],
            ['menu' => 'Operations', 'subject' => 'Charterer Profile', 'name' => 'ops-charterer-profile-edit'],
            ['menu' => 'Operations', 'subject' => 'Charterer Profile', 'name' => 'ops-charterer-profile-delete'],
            ['menu' => 'Operations', 'subject' => 'Charterer Contract', 'name' => 'ops-charterer-contract-view'],
            ['menu' => 'Operations', 'subject' => 'Charterer Contract', 'name' => 'ops-charterer-contract-create'],
            ['menu' => 'Operations', 'subject' => 'Charterer Contract', 'name' => 'ops-charterer-contract-edit'],
            ['menu' => 'Operations', 'subject' => 'Charterer Contract', 'name' => 'ops-charterer-contract-delete'],
            ['menu' => 'Operations', 'subject' => 'Delivery and Redelivery', 'name' => 'ops-delivery-redelivery-view'],
            ['menu' => 'Operations', 'subject' => 'Delivery and Redelivery', 'name' => 'ops-delivery-redelivery-create'],
            ['menu' => 'Operations', 'subject' => 'Delivery and Redelivery', 'name' => 'ops-delivery-redelivery-edit'],
            ['menu' => 'Operations', 'subject' => 'Delivery and Redelivery', 'name' => 'ops-delivery-redelivery-delete'],
            ['menu' => 'Operations', 'subject' => 'Charterer Invoice', 'name' => 'ops-charterer-invoice-view'],
            ['menu' => 'Operations', 'subject' => 'Charterer Invoice', 'name' => 'ops-charterer-invoice-create'],
            ['menu' => 'Operations', 'subject' => 'Charterer Invoice', 'name' => 'ops-charterer-invoice-edit'],
            ['menu' => 'Operations', 'subject' => 'Charterer Invoice', 'name' => 'ops-charterer-invoice-delete'],
            ['menu' => 'Operations', 'subject' => 'Voyage', 'name' => 'ops-voyage-view'],
            ['menu' => 'Operations', 'subject' => 'Voyage', 'name' => 'ops-voyage-create'],
            ['menu' => 'Operations', 'subject' => 'Voyage', 'name' => 'ops-voyage-edit'],
            ['menu' => 'Operations', 'subject' => 'Voyage', 'name' => 'ops-voyage-delete'],
            ['menu' => 'Operations', 'subject' => 'Contract Assign', 'name' => 'ops-contract-assign-view'],
            ['menu' => 'Operations', 'subject' => 'Contract Assign', 'name' => 'ops-contract-assign-create'],
            ['menu' => 'Operations', 'subject' => 'Contract Assign', 'name' => 'ops-contract-assign-edit'],
            ['menu' => 'Operations', 'subject' => 'Contract Assign', 'name' => 'ops-contract-assign-delete'],
            ['menu' => 'Operations', 'subject' => 'Lighterage Noon Report', 'name' => 'ops-lighterage-noon-report-view'],
            ['menu' => 'Operations', 'subject' => 'Lighterage Noon Report', 'name' => 'ops-lighterage-noon-report-create'],
            ['menu' => 'Operations', 'subject' => 'Lighterage Noon Report', 'name' => 'ops-lighterage-noon-report-edit'],
            ['menu' => 'Operations', 'subject' => 'Lighterage Noon Report', 'name' => 'ops-lighterage-noon-report-delete'],
            ['menu' => 'Operations', 'subject' => 'Bulk Noon Report', 'name' => 'ops-bulk-noon-report-view'],
            ['menu' => 'Operations', 'subject' => 'Bulk Noon Report', 'name' => 'ops-bulk-noon-report-create'],
            ['menu' => 'Operations', 'subject' => 'Bulk Noon Report', 'name' => 'ops-bulk-noon-report-edit'],
            ['menu' => 'Operations', 'subject' => 'Bulk Noon Report', 'name' => 'ops-bulk-noon-report-delete'],
            ['menu' => 'Operations', 'subject' => 'Voyage Boat Note', 'name' => 'ops-voyage-boat-note-view'],
            ['menu' => 'Operations', 'subject' => 'Voyage Boat Note', 'name' => 'ops-voyage-boat-note-create'],
            ['menu' => 'Operations', 'subject' => 'Voyage Boat Note', 'name' => 'ops-voyage-boat-note-edit'],
            ['menu' => 'Operations', 'subject' => 'Voyage Boat Note', 'name' => 'ops-voyage-boat-note-delete'],
            ['menu' => 'Operations', 'subject' => 'Voyage Budget', 'name' => 'ops-voyage-budget-view'],
            ['menu' => 'Operations', 'subject' => 'Voyage Budget', 'name' => 'ops-voyage-budget-create'],
            ['menu' => 'Operations', 'subject' => 'Voyage Budget', 'name' => 'ops-voyage-budget-edit'],
            ['menu' => 'Operations', 'subject' => 'Voyage Budget', 'name' => 'ops-voyage-budget-delete'],
            ['menu' => 'Operations', 'subject' => 'Voyage Expense', 'name' => 'ops-voyage-expense-view'],
            ['menu' => 'Operations', 'subject' => 'Voyage Expense', 'name' => 'ops-voyage-expense-create'],
            ['menu' => 'Operations', 'subject' => 'Voyage Expense', 'name' => 'ops-voyage-expense-edit'],
            ['menu' => 'Operations', 'subject' => 'Voyage Expense', 'name' => 'ops-voyage-expense-delete'],
            ['menu' => 'Operations', 'subject' => 'Purchase Requisition', 'name' => 'ops-purchase-requisition-view'],
            ['menu' => 'Operations', 'subject' => 'Purchase Requisition', 'name' => 'ops-purchase-requisition-create'],
            ['menu' => 'Operations', 'subject' => 'Purchase Requisition', 'name' => 'ops-purchase-requisition-edit'],
            ['menu' => 'Operations', 'subject' => 'Purchase Requisition', 'name' => 'ops-purchase-requisition-delete'],
            ['menu' => 'Operations', 'subject' => 'Vessel Bunker', 'name' => 'ops-vessel-bunker-view'],
            ['menu' => 'Operations', 'subject' => 'Vessel Bunker', 'name' => 'ops-vessel-bunker-create'],
            ['menu' => 'Operations', 'subject' => 'Vessel Bunker', 'name' => 'ops-vessel-bunker-edit'],
            ['menu' => 'Operations', 'subject' => 'Vessel Bunker', 'name' => 'ops-vessel-bunker-delete'],
            ['menu' => 'Operations', 'subject' => 'Bunker Bill', 'name' => 'ops-bunker-bill-view'],
            ['menu' => 'Operations', 'subject' => 'Bunker Bill', 'name' => 'ops-bunker-bill-create'],
            ['menu' => 'Operations', 'subject' => 'Bunker Bill', 'name' => 'ops-bunker-bill-edit'],
            ['menu' => 'Operations', 'subject' => 'Bunker Bill', 'name' => 'ops-bunker-bill-delete'],
            ['menu' => 'Operations', 'subject' => 'Voyage Bunker Report', 'name' => 'ops-voyage-bunker-report'],
            ['menu' => 'Operations', 'subject' => 'Vessel Bunker Report', 'name' => 'ops-vessel-bunker-report'],
            ['menu' => 'Operations', 'subject' => 'Lighterage Voyage Report', 'name' => 'ops-lighterage-voyage-report'],
            ['menu' => 'Operations', 'subject' => 'Bulk Voyage Report', 'name' => 'ops-bulk-voyage-report'],
            ['menu' => 'Operations', 'subject' => 'Port  Wise Expense Report', 'name' => 'ops-port-wise-expense-report'],
            ['menu' => 'Operations', 'subject' => 'Budget vs Expense Report', 'name' => 'ops-budget-vs-expense-report'],
            ['menu' => 'Operations', 'subject' => 'Month Wise Expense Report', 'name' => 'ops-month-wise-expense-report'],
            
        ];

        Permission::insert($operationPermissions);
    }
}
