import useHeroIcon from "../../assets/heroIcon";
const icons = useHeroIcon();

export default [
    {
        route: '',
        label: 'Accounts',
        preIcon: icons.Calculator,
        postIcon: icons.DownArrow,
        is_active: false,
        is_open: false,
        permissionKey: '',
        subMenu: [
            {
                route: '',
                label: 'Configurations',
                preIcon: '',
                postIcon: icons.DownArrow,
                is_active: false,
                is_open: false,
                permissionKey: ['acc-cost-center-view', 'acc-balance-income-line-view', 'acc-chart-of-account-view', 'acc-opening-balance-view','acc-bank-account-view','acc-salary-head-view','acc-cash-account-view'],
                subSubMenu: [
                    {
                        route: 'acc.cost-centers.index',
                        label: 'Cost Centers',
                        preIcon: '',
                        postIcon: icons.DownArrow,
                        is_active: false,
                        is_open: false,
                        permissionKey: 'acc-cost-center-view',
                    },
                    {
                        route: 'acc.balance-income-lines.index',
                        label: 'Balance Income Lines',
                        preIcon: '',
                        postIcon: icons.DownArrow,
                        is_active: false,
                        is_open: false,
                        permissionKey: 'acc-balance-income-line-view',
                    },
                    {
                        route: 'acc.chart-of-accounts.index',
                        label: 'Chart of Accounts',
                        preIcon: '',
                        postIcon: icons.DownArrow,
                        is_active: false,
                        is_open: false,
                        permissionKey: 'acc-chart-of-account-view',
                    },
                    {
                        route: 'acc.opening-balances.index',
                        label: 'Opening Balance',
                        preIcon: '',
                        postIcon: icons.DownArrow,
                        is_active: false,
                        is_open: false,
                        permissionKey: 'acc-opening-balance-view',
                    },
                    {
                        route: 'acc.bank-accounts.index',
                        label: 'Bank Accounts',
                        preIcon: '',
                        postIcon: icons.DownArrow,
                        is_active: false,
                        is_open: false,
                        permissionKey: 'acc-bank-account-view',
                    },
                    {
                        route: 'acc.salary-heads.index',
                        label: 'Salary Heads',
                        preIcon: '',
                        postIcon: icons.DownArrow,
                        is_active: false,
                        is_open: false,
                        permissionKey: 'acc-salary-head-view',
                    },
                    {
                        route: 'acc.cash-accounts.index',
                        label: 'Cash Accounts',
                        preIcon: '',
                        postIcon: icons.DownArrow,
                        is_active: false,
                        is_open: false,
                        permissionKey: 'acc-cash-account-view',
                    },
                ],
            },
            {
                route: 'acc.transactions.index',
                label: 'Vouchers',
                preIcon: '',
                postIcon: icons.DownArrow,
                is_active: false,
                is_open: false,
                permissionKey: 'acc-voucher-view',
                subSubMenu: [],
            },
            {
                route: 'acc.bank-reconciliation.index',
                label: 'Bank Reconciliation',
                preIcon: '',
                postIcon: icons.DownArrow,
                is_active: false,
                is_open: false,
                permissionKey: 'acc-bank-reconciliation',
                subSubMenu: [],
            },
            {
                route: 'acc.loans.index',
                label: 'Loans',
                preIcon: '',
                postIcon: icons.DownArrow,
                is_active: false,
                is_open: false,
                permissionKey: 'acc-loan-view',
                subSubMenu: [],
            },
            {
                route: 'acc.loan-received.index',
                label: 'Loan Received',
                preIcon: '',
                postIcon: icons.DownArrow,
                is_active: false,
                is_open: false,
                permissionKey: 'acc-loan-received-view',
                subSubMenu: [],
            },
            {
                route: 'acc.fixed-assets.index',
                label: 'Fixed Assets',
                preIcon: '',
                postIcon: icons.DownArrow,
                is_active: false,
                is_open: false,
                permissionKey: 'acc-fixed-asset-view',
                subSubMenu: [],
            },
            {
                route: 'acc.depreciations.index',
                label: 'Depreciations',
                preIcon: '',
                postIcon: icons.DownArrow,
                is_active: false,
                is_open: false,
                permissionKey: 'acc-depreciation-view',
                subSubMenu: [],
            },
            {
                route: 'acc.cash-requisitions.index',
                label: 'Cash Requisitions',
                preIcon: '',
                postIcon: icons.DownArrow,
                is_active: false,
                is_open: false,
                permissionKey: 'acc-cash-requisition-view',
                subSubMenu: [],
            },
            {
                route: 'acc.advance-adjustments.index',
                label: 'Advance Adjustments',
                preIcon: '',
                postIcon: icons.DownArrow,
                is_active: false,
                is_open: false,
                permissionKey: 'acc-advance-adjustment-view',
                subSubMenu: [],
            },
            {
                route: 'acc.administrative-salaries.index',
                label: 'Salary',
                preIcon: '',
                postIcon: icons.DownArrow,
                is_active: false,
                is_open: false,
                permissionKey: 'acc-salary-view',
                subSubMenu: [],
            },
            {
                route: '',
                label: 'AIS Reports',
                preIcon: '',
                postIcon: icons.DownArrow,
                is_active: false,
                is_open: false,
                permissionKey: ['acc-balance-sheet','acc-income-statement','acc-ledger','acc-trial-balance','acc-day-book','acc-fixed-asset-statement','acc-cost-center-summary','acc-cost-center-breakup','acc-receipt-payment'],
                subSubMenu: [
                    {
                        route: 'acc.ais-reports.balance-sheet',
                        label: 'Balance Sheet',
                        preIcon: '',
                        postIcon: icons.DownArrow,
                        is_active: false,
                        is_open: false,
                        permissionKey: 'acc-balance-sheet',
                        subSubMenu: [],
                    },
                    {
                        route: 'acc.ais-reports.income-statement',
                        label: 'Income Statement',
                        preIcon: '',
                        postIcon: icons.DownArrow,
                        is_active: false,
                        is_open: false,
                        permissionKey: 'acc-income-statement',
                        subSubMenu: [],
                    },
                    {
                        route: 'acc.ais-reports.ledger',
                        label: 'Ledger',
                        preIcon: '',
                        postIcon: icons.DownArrow,
                        is_active: false,
                        is_open: false,
                        permissionKey: 'acc-ledger',
                        subSubMenu: [],
                    },
                    {
                        route: 'acc.ais-reports.trial-balance',
                        label: 'Trial Balance',
                        preIcon: '',
                        postIcon: icons.DownArrow,
                        is_active: false,
                        is_open: false,
                        permissionKey: 'acc-trial-balance',
                        subSubMenu: [],
                    },
                    {
                        route: 'acc.ais-reports.day-book',
                        label: 'Day Book',
                        preIcon: '',
                        postIcon: icons.DownArrow,
                        is_active: false,
                        is_open: false,
                        permissionKey: 'acc-day-book',
                        subSubMenu: [],
                    },
                    {
                        route: 'acc.ais-reports.fixed-asset-statement',
                        label: 'Fixed Asset Statement',
                        preIcon: '',
                        postIcon: icons.DownArrow,
                        is_active: false,
                        is_open: false,
                        permissionKey: 'acc-fixed-asset-statement',
                        subSubMenu: [],
                    },
                    {
                        route: 'acc.ais-reports.cost-center-summary',
                        label: 'Cost Center Summary',
                        preIcon: '',
                        postIcon: icons.DownArrow,
                        is_active: false,
                        is_open: false,
                        permissionKey: 'acc-cost-center-summary',
                        subSubMenu: [],
                    },
                    {
                        route: 'acc.ais-reports.cost-center-breakup',
                        label: 'Cost Center Breakup',
                        preIcon: '',
                        postIcon: icons.DownArrow,
                        is_active: false,
                        is_open: false,
                        permissionKey: 'acc-cost-center-breakup',
                        subSubMenu: [],
                    },
                    {
                        route: 'acc.ais-reports.receipt-payment-statement',
                        label: 'Receipt & Payment',
                        preIcon: '',
                        postIcon: icons.DownArrow,
                        is_active: false,
                        is_open: false,
                        permissionKey: 'acc-receipt-payment',
                        subSubMenu: [],
                    },

                    // {
                    //     route: 'crw.vesselRequiredCrews.index',
                    //     label: 'Cost Center Breakup',
                    //     preIcon: '',
                    //     postIcon: icons.DownArrow,
                    //     is_active: false,
                    //     is_open: false,
                    //     permissionKey: '',
                    //     subSubMenu: [],
                    // },
                    // {
                    //     route: 'crw.vesselRequiredCrews.index',
                    //     label: 'Receipt & Payment Statement',
                    //     preIcon: '',
                    //     postIcon: icons.DownArrow,
                    //     is_active: false,
                    //     is_open: false,
                    //     permissionKey: '',
                    //     subSubMenu: [],
                    // },
                ],
            },
        ]
    },
];