import useHeroIcon from "../../assets/heroIcon";
const icons = useHeroIcon();

export default [
    {
        route: '',
        label: 'Crew Management',
        preIcon: icons.CrewDriver,
        postIcon: icons.DownArrow,
        is_active: false,
        is_open: false,
        permissionKey: '',
        subMenu: [
            {
                route: 'crw.ranks.index',
                label: 'Ranks',
                preIcon: '',
                postIcon: icons.DownArrow,
                is_active: false,
                is_open: false,
                permissionKey: 'crw-rank-view',
                subSubMenu: [],
            },
            {
                route: 'crw.vesselParticulars.index',
                label: 'Vessel Particulars',
                preIcon: '',
                postIcon: icons.DownArrow,
                is_active: false,
                is_open: false,
                permissionKey: 'crw-vessel-particular-view',
                subSubMenu: [],
            },
            {
                route: 'crw.policies.index',
                label: 'Policies',
                preIcon: '',
                postIcon: icons.DownArrow,
                is_active: false,
                is_open: false,
                permissionKey: 'crw-policy-view',
                subSubMenu: [],
            },
            {
                route: 'crw.checklists.index',
                label: 'Onboard Checklist',
                preIcon: '',
                postIcon: icons.DownArrow,
                is_active: false,
                is_open: false,
                permissionKey: 'crw-onboard-checklist-view',
                subSubMenu: [],
            },
            {
                route: 'crw.vesselRequiredCrews.index',
                label: 'Vessel Crew Manning',
                preIcon: '',
                postIcon: icons.DownArrow,
                is_active: false,
                is_open: false,
                permissionKey: 'crw-vessel-crew-manning-view',
                subSubMenu: [],
            },
            {
                route: 'crw.crewRequisitions.index',
                label: 'Crew Requisitions',
                preIcon: '',
                postIcon: icons.DownArrow,
                is_active: false,
                is_open: false,
                permissionKey: 'crw-requisition-view',
                subSubMenu: [],
            },
            {
                route: 'crw.recruitmentApprovals.index',
                label: 'Recruitment Approvals',
                preIcon: '',
                postIcon: icons.DownArrow,
                is_active: false,
                is_open: false,
                permissionKey: 'crw-recruitment-approval-view',
                subSubMenu: [],
            },
            {
                route: '',
                label: 'Agency',
                preIcon: '',
                postIcon: icons.DownArrow,
                is_active: false,
                is_open: false,
                permissionKey: '',
                subSubMenu: [
                    {
                        route: 'crw.agencies.index',
                        label: 'Profiles',
                        preIcon: '',
                        postIcon: icons.DownArrow,
                        is_active: false,
                        is_open: false,
                        permissionKey: 'crw-agency-profile-view',
                        subSubMenu: [],
                    },
                    {
                        route: 'crw.agencyContracts.index',
                        label: 'Contracts',
                        preIcon: '',
                        postIcon: icons.DownArrow,
                        is_active: false,
                        is_open: false,
                        permissionKey: 'crw-agency-contract-view',
                        subSubMenu: [],
                    },
                    {
                        route: 'crw.agencyBills.index',
                        label: 'Bills',
                        preIcon: '',
                        postIcon: icons.DownArrow,
                        is_active: false,
                        is_open: false,
                        permissionKey: 'crw-agency-bill-view',
                        subSubMenu: [],
                    },
                ],
            },
            {
                route: 'crw.profiles.index',
                label: 'Crew Profiles',
                preIcon: '',
                postIcon: icons.DownArrow,
                is_active: false,
                is_open: false,
                permissionKey: 'crw-profile-view',
                subSubMenu: [],
            },
            {
                route: '',
                label: 'Crew Documents',
                preIcon: '',
                postIcon: icons.DownArrow,
                is_active: false,
                is_open: false,
                permissionKey: '',
                subSubMenu: [
                    {
                        route: 'crw.documents.create',
                        label: 'Add Document',
                        preIcon: '',
                        postIcon: icons.DownArrow,
                        is_active: false,
                        is_open: false,
                        permissionKey: 'crw-document-view',
                        subSubMenu: [],
                    },
                    {
                        route: 'crw.renew-schedules.index',
                        label: 'Renew Schedule',
                        preIcon: '',
                        postIcon: icons.DownArrow,
                        is_active: false,
                        is_open: false,
                        permissionKey: 'crw-document-renew',
                        subSubMenu: [],
                    },
                ],
            },
            {
                route: 'crw.crewAssigns.index',
                label: 'Crew Assignment',
                preIcon: '',
                postIcon: icons.DownArrow,
                is_active: false,
                is_open: false,
                permissionKey: 'crw-assignment-view',
                subSubMenu: [],
            },
            {
                route: 'crw.crwAttendances.index',
                label: 'Crew Attendance',
                preIcon: '',
                postIcon: icons.DownArrow,
                is_active: false,
                is_open: false,
                permissionKey: 'crw-attendance-view',
                subSubMenu: [],
            },
            {
                route: 'crw.incidentRecords.index',
                label: 'Incidents Records',
                preIcon: '',
                postIcon: icons.DownArrow,
                is_active: false,
                is_open: false,
                permissionKey: 'crw-incident-record-view',
                subSubMenu: [],
            },
            {
                route: 'crw.crewSalaryStructures.index',
                label: 'Crew Salary Structure',
                preIcon: '',
                postIcon: icons.DownArrow,
                is_active: false,
                is_open: false,
                permissionKey: 'crw-salary-structure-view',
                subSubMenu: [],
            },
            {
                route: 'crw.crewBankAccounts.index',
                label: 'Crew Bank Accounts',
                preIcon: '',
                postIcon: icons.DownArrow,
                is_active: false,
                is_open: false,
                permissionKey: 'crw-bank-account-view',
                subSubMenu: [],
            },
            {
                route: '',
                label: 'Salary',
                preIcon: '',
                postIcon: icons.DownArrow,
                is_active: false,
                is_open: false,
                permissionKey: '',
                subSubMenu: [
                    {
                        route: 'crw.crewPayrollBatches.create',
                        label: 'Generate Salary',
                        preIcon: '',
                        postIcon: icons.DownArrow,
                        is_active: false,
                        is_open: false,
                        permissionKey: 'crw-salary-create',
                        subSubMenu: [],
                    },
                    {
                        route: 'crw.crewPayrollBatches.index',
                        label: 'Salary List',
                        preIcon: '',
                        postIcon: icons.DownArrow,
                        is_active: false,
                        is_open: false,
                        permissionKey: 'crw-salary-view',
                        subSubMenu: [],
                    },
                ],
            },
            // {
            //     route: 'administration.users.index',
            //     label: 'Appraisal Records',
            //     preIcon: '',
            //     postIcon: icons.DownArrow,
            //     is_active: false,
            //     is_open: false,
            //     permissionKey: '',
            //     subSubMenu: [],
            // },
            // {
            //     route: 'administration.users.index',
            //     label: 'Rest Hour Records',
            //     preIcon: '',
            //     postIcon: icons.DownArrow,
            //     is_active: false,
            //     is_open: false,
            //     permissionKey: '',
            //     subSubMenu: [],
            // },

            {
                route: 'crw.appraisal-forms.index',
                label: 'Appraisal Forms',
                preIcon: '',
                postIcon: icons.DownArrow,
                is_active: false,
                is_open: false,
                permissionKey: 'crw-apprisal-form-view',
                subSubMenu: [],
            },
            {
                route: 'crw.appraisal-records.index',
                label: 'Appraisal Records',
                preIcon: '',
                postIcon: icons.DownArrow,
                is_active: false,
                is_open: false,
                permissionKey: 'crw-apprisal-record-view',
                subSubMenu: [],
            },

            {
                route: 'crw.rest-hour-records.index',
                label: 'Rest Hour',
                preIcon: '',
                postIcon: icons.DownArrow,
                is_active: false,
                is_open: false,
                permissionKey: 'crw-rest-hour-view',
                subSubMenu: [],
            },
            {
                route: 'crw.rest-hour-records.report',
                label: 'Rest Hour Records',
                preIcon: '',
                postIcon: icons.DownArrow,
                is_active: false,
                is_open: false,
                permissionKey: 'crw-rest-hour-record',
                subSubMenu: [],
            },
        ]
    },
];